### ISSUE TITLE
serde flatten breaks deserialization of hashmaps keyed with integers

### ISSUE THREAD

**Issue by Jarngreipr** [serde-rs/serde#2117]
Please allow me to explain the issue with a simple test case:

```
#[derive(Deserialize)]
struct Wrapper {
    #[serde(flatten)]
    inner: HashMap<u64, String>,
}

#[test]
fn deserialize_flattened_map() {
    let json = r#"{
        "1": "this type doesn't matter"
    }"#;
    
    let _inner: HashMap<u64, String> = serde_json::from_str(json).expect("succeeds");
    let _wrapper: Wrapper = serde_json::from_str(json).expect("fails with type error on key");
}
```

The above also occurs when the map is nested within another struct and that struct is flattened but the map itself is not.
I feel that this must be a bug, as without flattening the deserialization succeeds as expected.

**Comment by Mingun** [comment]
`#[serde(flatten)]` is completely broken. Avoid using it if you can. This is duplicate of #1183.

**Comment by jonasbb** [comment]
You can work around this by adding custom deserialization code. The attributes tell serde to parse the string into a number. This uses the [`serde_with`](https://github.com/jonasbb/serde_with) crate.

```rust
#[serde_with::serde_as]
#[derive(Deserialize)]
struct Wrapper {
    #[serde(flatten)]
    #[serde_as(as = "HashMap<serde_with::DisplayFromStr, _>")]
    inner: HashMap<u64, String>,
}
```

**Comment by mitsuhiko** [comment]
> `#[serde(flatten)]` is completely broken. Avoid using it if you can. This is duplicate of #1183.

The problem is not `flatten` but any internal buffering. That is prominently used for `flatten` but it's by far not the only serde feature that uses this mode.

**Comment by Mingun** [comment]
Yes, of course. But `flatten` also haw it own design flaws. For example, compiler does not check that type that you trying to flatten is really flattable -- you will get a runtime error.

I tried to fix that and I even made that in almost backward-compatible manner (at least, it fully backward-compatible if you don't try to flatten field with the type for which `Deserialize` is manually implemented. But even in that case it would indicate a bug in your types rather then a real incompatibility). But I think this will be wrong approach because flattenability is a trait of type, not the operation (I have implemented new traits in the `Deserialize` derive) and with my approach compiler still does not checking the correctness of `flatten` if you don't deriving/implementing `Deserialize`.

**Comment by mitsuhiko** [comment]
It's not possible to check the flattenability at compile time because you cannot "inspect" the serializer/deserializer. I don't think that's a problem with flatten however, that's just a limitation of how serde works.

**Comment by Mingun** [comment]
It is possible if the type implement a specific trait that required to be implemented in order to `flatten` will work (i.e. it contains a method that (de)serializes flattened type into a storage). In my implementation I've implement such type in the `Deserialize` derive. Then you just cannot use the type that does not implement that trait with the `#[serde(flatten)]` attribute:

```rust
trait DeserializeEmbed: Deserialize {
  type Storage;
  fn from_storage(storage: &mut Self::Storage) -> Self;
}
struct Flattened {
  #[serde(flatten)]
  flatten: HashMap<str, str>,
  // ...other fields
}
impl DeserializeEmbed for Flattened {
  type Storage = ...;
  fn from_storage(storage: &mut Self::Storage) -> Self {
    let flatten: HashMap<str, str> = DeserializeEmbed::from_storage(&mut storage);
    // ...read other fields from `storage`
    Self { flatten, ... }
  }
}

**Comment by mitsuhiko** [comment]
Which in turn makes the feature very limited. I went down this path when I originally wrote the flatten support and it was very limiting and did not solve an real issues.

**Comment by Mingun** [comment]
You mean using special trait for indicating that type is able to be flattened? Limitations in that approach is by design: compiler should prevent you from doing wrong things and that the only right way to do that. What kinds of real issues you couldn't solve with that approach?

**Comment by dtolnay** [comment]
I'll close this as a duplicate of #1183.
